from distutils.core import setup, Extension

SPP_module = Extension(
   '_SPP',
   sources=['SPP_wrap.cxx', 'SPP.cpp'], # SPP_wrap.cxx is going to be generated by swig
)

setup (
	name        = 'SPP',
	version     = '0.0',
	author      = "Pablo",
	description = "SPP swig",
	ext_modules = [SPP_module],
	py_modules  = ["SPP"], # name of module that we're going import
)