# This file was automatically generated by SWIG (http://www.swig.org).
# Version 3.0.12
#
# Do not make changes to this file unless you know what you are doing--modify
# the SWIG interface file instead.

from sys import version_info as _swig_python_version_info
if _swig_python_version_info >= (2, 7, 0):
    def swig_import_helper():
        import importlib
        pkg = __name__.rpartition('.')[0]
        mname = '.'.join((pkg, '_SPP')).lstrip('.')
        try:
            return importlib.import_module(mname)
        except ImportError:
            return importlib.import_module('_SPP')
    _SPP = swig_import_helper()
    del swig_import_helper
elif _swig_python_version_info >= (2, 6, 0):
    def swig_import_helper():
        from os.path import dirname
        import imp
        fp = None
        try:
            fp, pathname, description = imp.find_module('_SPP', [dirname(__file__)])
        except ImportError:
            import _SPP
            return _SPP
        try:
            _mod = imp.load_module('_SPP', fp, pathname, description)
        finally:
            if fp is not None:
                fp.close()
        return _mod
    _SPP = swig_import_helper()
    del swig_import_helper
else:
    import _SPP
del _swig_python_version_info

try:
    _swig_property = property
except NameError:
    pass  # Python < 2.2 doesn't have 'property'.

try:
    import builtins as __builtin__
except ImportError:
    import __builtin__

def _swig_setattr_nondynamic(self, class_type, name, value, static=1):
    if (name == "thisown"):
        return self.this.own(value)
    if (name == "this"):
        if type(value).__name__ == 'SwigPyObject':
            self.__dict__[name] = value
            return
    method = class_type.__swig_setmethods__.get(name, None)
    if method:
        return method(self, value)
    if (not static):
        if _newclass:
            object.__setattr__(self, name, value)
        else:
            self.__dict__[name] = value
    else:
        raise AttributeError("You cannot add attributes to %s" % self)


def _swig_setattr(self, class_type, name, value):
    return _swig_setattr_nondynamic(self, class_type, name, value, 0)


def _swig_getattr(self, class_type, name):
    if (name == "thisown"):
        return self.this.own()
    method = class_type.__swig_getmethods__.get(name, None)
    if method:
        return method(self)
    raise AttributeError("'%s' object has no attribute '%s'" % (class_type.__name__, name))


def _swig_repr(self):
    try:
        strthis = "proxy of " + self.this.__repr__()
    except __builtin__.Exception:
        strthis = ""
    return "<%s.%s; %s >" % (self.__class__.__module__, self.__class__.__name__, strthis,)

try:
    _object = object
    _newclass = 1
except __builtin__.Exception:
    class _object:
        pass
    _newclass = 0

import collections
class SwigPyIterator(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SwigPyIterator, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SwigPyIterator, name)

    def __init__(self, *args, **kwargs):
        raise AttributeError("No constructor defined - class is abstract")
    __repr__ = _swig_repr
    __swig_destroy__ = _SPP.delete_SwigPyIterator
    __del__ = lambda self: None

    def value(self):
        return _SPP.SwigPyIterator_value(self)

    def incr(self, n=1):
        return _SPP.SwigPyIterator_incr(self, n)

    def decr(self, n=1):
        return _SPP.SwigPyIterator_decr(self, n)

    def distance(self, x):
        return _SPP.SwigPyIterator_distance(self, x)

    def equal(self, x):
        return _SPP.SwigPyIterator_equal(self, x)

    def copy(self):
        return _SPP.SwigPyIterator_copy(self)

    def next(self):
        return _SPP.SwigPyIterator_next(self)

    def __next__(self):
        return _SPP.SwigPyIterator___next__(self)

    def previous(self):
        return _SPP.SwigPyIterator_previous(self)

    def advance(self, n):
        return _SPP.SwigPyIterator_advance(self, n)

    def __eq__(self, x):
        return _SPP.SwigPyIterator___eq__(self, x)

    def __ne__(self, x):
        return _SPP.SwigPyIterator___ne__(self, x)

    def __iadd__(self, n):
        return _SPP.SwigPyIterator___iadd__(self, n)

    def __isub__(self, n):
        return _SPP.SwigPyIterator___isub__(self, n)

    def __add__(self, n):
        return _SPP.SwigPyIterator___add__(self, n)

    def __sub__(self, *args):
        return _SPP.SwigPyIterator___sub__(self, *args)
    def __iter__(self):
        return self
SwigPyIterator_swigregister = _SPP.SwigPyIterator_swigregister
SwigPyIterator_swigregister(SwigPyIterator)

PI = _SPP.PI

def normalize(x, y, z=0):
    return _SPP.normalize(x, y, z)
normalize = _SPP.normalize
class SPP(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, SPP, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, SPP, name)
    __repr__ = _swig_repr
    __swig_setmethods__["cell_centers"] = _SPP.SPP_cell_centers_set
    __swig_getmethods__["cell_centers"] = _SPP.SPP_cell_centers_get
    if _newclass:
        cell_centers = _swig_property(_SPP.SPP_cell_centers_get, _SPP.SPP_cell_centers_set)
    __swig_setmethods__["cell_directions"] = _SPP.SPP_cell_directions_set
    __swig_getmethods__["cell_directions"] = _SPP.SPP_cell_directions_get
    if _newclass:
        cell_directions = _swig_property(_SPP.SPP_cell_directions_get, _SPP.SPP_cell_directions_set)
    __swig_setmethods__["dt"] = _SPP.SPP_dt_set
    __swig_getmethods__["dt"] = _SPP.SPP_dt_get
    if _newclass:
        dt = _swig_property(_SPP.SPP_dt_get, _SPP.SPP_dt_set)
    __swig_setmethods__["radius"] = _SPP.SPP_radius_set
    __swig_getmethods__["radius"] = _SPP.SPP_radius_get
    if _newclass:
        radius = _swig_property(_SPP.SPP_radius_get, _SPP.SPP_radius_set)

    def __init__(self, dt_c=0.01, gamma_c=1, gamma_s_c=1, radius_c=1, W_s_c=1, W_c_c=0, f_pol_c=1, D_r_c=1, F_m_c=1, z_axis_c=True):
        this = _SPP.new_SPP(dt_c, gamma_c, gamma_s_c, radius_c, W_s_c, W_c_c, f_pol_c, D_r_c, F_m_c, z_axis_c)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def addCell(self, pos_x=0, pos_y=0, pos_z=0, dir_1=0, dir_2=0, dir_3=3.1415):
        return _SPP.SPP_addCell(self, pos_x, pos_y, pos_z, dir_1, dir_2, dir_3)

    def step(self):
        return _SPP.SPP_step(self)

    def find_contacts(self):
        return _SPP.SPP_find_contacts(self)

    def move_cells(self, contacts):
        return _SPP.SPP_move_cells(self, contacts)

    def repolarize(self):
        return _SPP.SPP_repolarize(self)
    __swig_destroy__ = _SPP.delete_SPP
    __del__ = lambda self: None
SPP_swigregister = _SPP.SPP_swigregister
SPP_swigregister(SPP)

class floatVector(_object):
    __swig_setmethods__ = {}
    __setattr__ = lambda self, name, value: _swig_setattr(self, floatVector, name, value)
    __swig_getmethods__ = {}
    __getattr__ = lambda self, name: _swig_getattr(self, floatVector, name)
    __repr__ = _swig_repr

    def iterator(self):
        return _SPP.floatVector_iterator(self)
    def __iter__(self):
        return self.iterator()

    def __nonzero__(self):
        return _SPP.floatVector___nonzero__(self)

    def __bool__(self):
        return _SPP.floatVector___bool__(self)

    def __len__(self):
        return _SPP.floatVector___len__(self)

    def __getslice__(self, i, j):
        return _SPP.floatVector___getslice__(self, i, j)

    def __setslice__(self, *args):
        return _SPP.floatVector___setslice__(self, *args)

    def __delslice__(self, i, j):
        return _SPP.floatVector___delslice__(self, i, j)

    def __delitem__(self, *args):
        return _SPP.floatVector___delitem__(self, *args)

    def __getitem__(self, *args):
        return _SPP.floatVector___getitem__(self, *args)

    def __setitem__(self, *args):
        return _SPP.floatVector___setitem__(self, *args)

    def pop(self):
        return _SPP.floatVector_pop(self)

    def append(self, x):
        return _SPP.floatVector_append(self, x)

    def empty(self):
        return _SPP.floatVector_empty(self)

    def size(self):
        return _SPP.floatVector_size(self)

    def swap(self, v):
        return _SPP.floatVector_swap(self, v)

    def begin(self):
        return _SPP.floatVector_begin(self)

    def end(self):
        return _SPP.floatVector_end(self)

    def rbegin(self):
        return _SPP.floatVector_rbegin(self)

    def rend(self):
        return _SPP.floatVector_rend(self)

    def clear(self):
        return _SPP.floatVector_clear(self)

    def get_allocator(self):
        return _SPP.floatVector_get_allocator(self)

    def pop_back(self):
        return _SPP.floatVector_pop_back(self)

    def erase(self, *args):
        return _SPP.floatVector_erase(self, *args)

    def __init__(self, *args):
        this = _SPP.new_floatVector(*args)
        try:
            self.this.append(this)
        except __builtin__.Exception:
            self.this = this

    def push_back(self, x):
        return _SPP.floatVector_push_back(self, x)

    def front(self):
        return _SPP.floatVector_front(self)

    def back(self):
        return _SPP.floatVector_back(self)

    def assign(self, n, x):
        return _SPP.floatVector_assign(self, n, x)

    def resize(self, *args):
        return _SPP.floatVector_resize(self, *args)

    def insert(self, *args):
        return _SPP.floatVector_insert(self, *args)

    def reserve(self, n):
        return _SPP.floatVector_reserve(self, n)

    def capacity(self):
        return _SPP.floatVector_capacity(self)
    __swig_destroy__ = _SPP.delete_floatVector
    __del__ = lambda self: None
floatVector_swigregister = _SPP.floatVector_swigregister
floatVector_swigregister(floatVector)

# This file is compatible with both classic and new-style classes.


